sources:
  # ───── 국내 (4) ─────
  - name: yonhap_tv
    bias: center         # 와이어/팩트 위주
    type: rss
    urls:
      - "http://www.yonhapnewstv.co.kr/browse/feed/"
      - "http://www.yonhapnewstv.co.kr/category/news/economy/feed/"

  - name: hankyung
    bias: market         # 투자/기업 친화 보도 비중↑
    type: rss
    urls:
      - "https://www.hankyung.com/feed/all-news"
      - "https://www.hankyung.com/feed/finance"

  - name: khan
    bias: center_left    # 비판적/사회이슈 비중↑
    type: rss
    urls:
      - "https://www.khan.co.kr/rss/rssdata/kh_news.xml"

  - name: news1
    bias: center
    type: google_news
    query: "site:news1.kr"

  # ───── 미국 (6) ─────
  - name: reuters
    bias: center         # 글로벌 와이어
    type: google_news
    query: "site:reuters.com"

  - name: ap
    bias: center         # 미국 와이어
    type: google_news
    query: "site:apnews.com"

  - name: cnbc
    bias: market
    type: google_news
    query: "site:cnbc.com"

  - name: bloomberg
    bias: market
    type: google_news
    query: "site:bloomberg.com"

  - name: wsj
    bias: center_right   # 보수/시장 친화 논조
    type: google_news
    query: "site:wsj.com"

  - name: nytimes
    bias: center_left
    type: google_news
    query: "site:nytimes.com"

  # ───── 그 외 해외 (3) ─────
  - name: guardian
    bias: center_left
    type: rss
    urls:
      - "https://www.theguardian.com/world/rss"
      - "https://www.theguardian.com/business/rss"

  - name: ft
    bias: market
    type: google_news
    query: "site:ft.com"

  - name: nikkei
    bias: market
    type: google_news
    query: "site:asia.nikkei.com"
